"""add_threshold_to_inventory

Revision ID: f2d4201937d4
Revises: 10614cadff73
Create Date: 2026-03-26 17:21:03.893597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d4201937d4'
down_revision: Union[str, Sequence[str], None] = '10614cadff73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('threshold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'threshold')
    # ### end Alembic commands ###
